#!/bin/bash
#d user-suite -endian:big NewWPILibJ
d user-suite -endian:big ../rollingthunder/WPILibJ
#ftp -u 10.0.0.2 tests/TestRobot/TestRobot.suite /ni-rt/system/
ftp -n 10.0.0.2 <<EOF
user guest guest
hash
#put NewWPILibJ/NewWPILibJ.suite /ni-rt/system/robot.suite
put ../rollingthunder/WPILibJ/WPILibJ.suite /ni-rt/system/robot.suite
quit
EOF
# end